### ISSUE TITLE
General documentation about the yaml file

### ISSUE THREAD

**Issue by kakila** [Jakski/sphinxcontrib-autoyaml#16]
I interleave comments explaining the contents of sections in a general way befroe documenting each of the fields, example:

```yaml
###
# This is a config file.
# 
# The idea is to use it to configure stuff.

###
# this is a field
my-field: 
   ###
   # This is a key
    key: 1

###
# The next fields describe things related to XXX.
# They should be used for YYY.

###
# this is another field
my-other-field: 
   ###
   # This is another key
    another-key: 2
```
All the comments that are not next to a field are not rendered by autoyaml. Is there a way to render these as well?
It is better for documenting the file to put those explanations in place, and not to repeat them in the documentation of the package.
