### ISSUE TITLE
Support for lists

### ISSUE THREAD

**Issue by PowerTester** [Jakski/sphinxcontrib-autoyaml#20]
Would it be possible to add support for parsing YAML lists without a parent key? Most Ansible yaml files will be in the form of a list.

Adding a key to the top of an Ansible file does 'work' as one might expect, but is not a valid Ansible playbook

Example that will parse correctly into reST
```
test3:
    ###
    # The :code:`test ansible` playbook 
  - name: test ansible
    tasks:
      ###
      # This is a task
    - name: value
      another: value
      ###
      # This is a task      
    - name: value
      another: value

```

However, most ansible playbooks and roles will not have a `test3:` parent key, and look more like the list below.

Example lists.yml:
```
  ###
  # The :code:`test ansible` playbook 
- name: test ansible
  tasks:
    ###
    # This is a task
  - name: value
    another: value
    ###
    # This is a task      
  - name: value
    another: value

```
