### ISSUE TITLE
Nesting the doc according to yaml's nesting

### ISSUE THREAD

**Issue by MartinHerren** [Jakski/sphinxcontrib-autoyaml#4]
Hello,

autoyaml seems to be an nice extension to document yaml files inside sphinx.

Unfortunately in the current version the generated doc is 'flat'. It would greatly enhance readability if it would be possible to 'nest' the documentation following yaml's file nesting.

**Comment by Jakski** [comment]
Hi,
currently YAML:

```yaml
###
# Level 1 variable description
variable:
  ###
  # Level 2 variable description
  subvar:
    ###
    # Level 3 variable description
    subsubvar: "test"
```

would render as:

```
variable

   Level 1 variable description

subvar

   Level 2 variable description

subsubvar

   Level 3 variable description
```
I assume your idea is to render it like:

```
variable

   Level 1 variable description

   subvar

      Level 2 variable description

      subsubvar

         Level 3 variable description
```
Am I right?
